#PRODUCTS
### Create an new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "brand": "Rolex",
  "model": "Datejust",
  "starting_price": 3000.00,
  "description": "lorem",
  "year": "2021",
  "diameter": 34,
  "material": "silver",
  "water_resistance": true,
  "auction_end": 1632391200000
}

### Create an new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "brand": "Casio",
  "model": "G-shock  GR-B200",
  "starting_price": 50.00,
  "description": "lorem",
  "year": "2021",
  "diameter": 54,
  "material": "plastic",
  "water_resistance": true,
  "auction_end": 1632650400000
}

### Create an new product
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "brand": "Breitling",
  "model": "Avanger automatic GMT",
  "starting_price": 2000.00,
  "description": "lorem",
  "year": "2021",
  "diameter": 43,
  "material": "Stainles steel",
  "water_resistance": true,
  "auction_end": 1632391200000
}

### Get all products
GET http://localhost:8080/api/products
Content-Type: application/json


### Get product by id
GET http://localhost:8080/api/products/1
Content-Type: application/json

### Update product with product ID 1
PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
  "brand": "Rolex",
  "model": "Datejust",
  "starting_price": 3000.00,
  "description": "lorem",
  "year": "2021",
  "diameter": 54,
  "material": "silver",
  "water_resistance": true
}

### Delete product with product ID 2
DELETE http://localhost:8080/api/products/2

#USERS

### Create a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstname": "Syon",
  "lastname": "Fopen",
  "Email": "syon.foppen@trimm.nl",
  "Password": "DitIsEenWachtwoord12345$",
  "admin": true

}

### Create a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstname": "Erel",
  "lastname": "cetin",
  "Email": "erel.cetin@gmail.com",
  "Password": "DitIsEenWachtwoord12345$"
}

### Create a new user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "firstname": "Henk",
  "lastname": "Pieter",
  "Email": "test@gmail.com",
  "Password": "DitIsEenWachtwoord12345$"

}


### Get user by ID
GET http://localhost:8080/api/users/1
Content-Type: application/json

### Update the user with id 1
PUT http://localhost:8080/api/users/1
Content-Type: application/json

{
  "firstname": "Syon",
  "lastname": "Foppen",
  "Email": "syon.foppen@trimm.nl",
  "Password": "DitIsEenWachtwoord12345$"
}

###Delete user with ID 2
DELETE http://localhost:8080/api/users/2
Content-Type: application/json


#bids
### Place a new bid on product with product id 1
POST http://localhost:8080/api/bids
Content-Type: application/json

{
  "Product_id": 1,
  "User_id": 1,
  "Amount": 3500.00
}
### Place a new bid on product with product id 1
POST http://localhost:8080/api/bids
Content-Type: application/json

{
  "Product_id": 2,
  "User_id": 2,
  "Amount": 60.00
}


### Delete a bid
DELETE http://localhost:8080/api/bids/1

